### ISSUE TITLE
latest 0.4.1 is not available in linux environment?

### ISSUE THREAD

**Issue by KoichiHashikawa** [r-spatial/classInt#10]
Hi!

I really appreciate classInt has been widely used in the community.
I recently tried to install an analysis package which requires the 0.4-1 version of classInt.
It seems that this version may not be able to be installed in my Linux computer.
If that is the case, can we expect that this version will be available to linux sometime soon.

thanks so much!

**Comment by edzer** [comment]
This should work without problems. What error messages do you see?

**Comment by KoichiHashikawa** [comment]
THanks for the reply.

I could see some error message in the terminal like

install.packages("classInt")
----------------------
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/garret/anaconda3/envs/Test/lib/R/library/KernSmooth/libs/KernSmooth.so':
  libRblas.so: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘classInt’
* removing ‘/home/garret/anaconda3/envs/Test/lib/R/library/classInt’
* restoring previous ‘/home/garret/anaconda3/envs/Test/lib/R/library/classInt’
---------------------------------------------------------------------

I sometimes have this error on some packages. Probably because I used conda (jupyter notebook).
conda install -c conda-forge r-classint
worked for me and now I have version 0.3.3, but conda community has not made 0.41 available yet.

**Comment by edzer** [comment]
Sounds like your problem is with r-anaconda, not with this particular package, as everthing works if you use R without anaconda.
