### ISSUE TITLE
error installing the package on R built with MKL

### ISSUE THREAD

**Issue by lmwang9527** [r-spatial/classInt#15]
I am installing the classInt package on R built with MKL and run an error and a couple of warnings. I appreciate it if anyone can provide any information that helps fix the issue.

The building snippet with the warnings and error is:

```
make[1]: Entering directory '/tmp/RtmpYnE2gy/R.INSTALL11d7869106e/classInt/src'
gfortran -fno-optimize-sibling-calls  -fpic  -m64 -I/opt/intel/compilers_and_libraries_2019.4.243/linux/mkl/include   -c fish1.f -o fish1.o
f951: Warning: Nonexistent include directory ‘/opt/intel/compilers_and_libraries_2019.4.243/linux/mkl/include’ [-Wmissing-include-dirs]
fish1.f:100:72:

  100 |          DO 10 I=1,M
      |                                                                        1
Warning: Fortran 2018 deleted feature: Shared DO termination label 10 at (1)
fish1.f:132:72:

  132 |    40 IWORK(I,1)=1
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 40 at (1)
gcc -I"/usr/include/R/" -DNDEBUG   -D_FORTIFY_SOURCE=2  -fpic  -m64 -I/opt/intel/compilers_and_libraries_2019.4.243/linux/mkl/include -march=x86-64 -mtune=generic -O2 -pipe -fno$
plt  -c init.c -o init.o
gcc -shared -L/usr/lib64/R/lib -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o classInt.so fish1.o init.o -lgfortran -limf -lm -lquadmath -L/usr/lib64/R/lib -lR
/usr/sbin/ld: cannot find -limf
collect2: error: ld returned 1 exit status
make[1]: *** [/usr/share/R//make/shlib.mk:6: classInt.so] Error 1
make[1]: Leaving directory '/tmp/RtmpYnE2gy/R.INSTALL11d7869106e/classInt/src'
ERROR: compilation failed for package ‘classInt’
* removing ‘/usr/lib/R/library/classInt’
```

It is an ArchLinux box with packages updated to the latest version. mkl and r-mkl are built and installed from ArchLinux User Repository (https://aur.archlinux.org/packages/r-mkl). The odd thing is that libimf.so is available at /opt/intel/lib, which is included /etc/ld.so.conf.d/intel-common-libs.conf.

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS/LAPACK: /opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1
```

A complete log of the installing stdout is available at https://gist.github.com/lmwang9527/48386437de1574aac45cb27725f129c7

Thanks!

**Comment by rsbivand** [comment]
I cannot help with MKL, I don't have access and would never use it if I did (usually degrades performance of **parallell** processes by competing for resources). I am not in principle willing to try to change the original code in `fish.f`, which is taken directly from the referenced source. Please try to compile `fish.f` to `fish.o` with the non-standards-compliant Fortran compiler you are using, and report what `R CMD config FC` and `R CMD config F77` show. 

My guess is that the compiler provides flags permitting the correct compilation of legacy code, but that the packager has forgotten to use them. It isn't up to me as maintainer to change legacy code to suit very marginal needs probably triggered by packager errors. Nothing in `fish.f` uses BLAS or LAPACK, so MKL has no reason to cause trouble.

**Comment by rsbivand** [comment]
The real problem is here:

```
gcc -shared -L/usr/lib64/R/lib -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o classInt.so fish1.o init.o -lgfortran -limf -lm -lquadmath -L/usr/lib64/R/lib -lR
/usr/sbin/ld: cannot find -limf
```

What does `R CMD config FLIBS` say? Is this a packaging problem? -limf is not needed by `fish.o`, but if using MKL needs it, it should be accompanied by `-L/opt/intel/lib`. Please ask the ArchLinux R packager.

**Comment by lmwang9527** [comment]
I am using gfortran as the compiler. Good to know that fish.f doesn't require libimf, so it seems a problem of the r-mkl package insert "-limf" option to the linker. 

```
$ R CMD config FLIBS
-lgfortran -limf -lm -lquadmath
```

I will dig into how to change this config in the ArchLinux R package. You can mark this issue as being closed. Thanks a lot for your help!

**Comment by lmwang9527** [comment]
To report back, the issue is fixed by editing /etc/R/Makeconf: 

`FCLIBS_XTRA = -L/opt/intel/lib`

**Comment by rsbivand** [comment]
Great, thanks for reporting back! `libimf.so` appears to add Intel versions of standard math library functions; the packager would need to check whether these implementations affect `make check` output and package check/test output.
