### ISSUE TITLE
Add box breaks as "box" style

### ISSUE THREAD

**Issue by angela-li** [r-spatial/classInt#18]
Would it be possible to add "box" as a style for class intervals? We've written preliminary code for this [here](https://spatialanalysis.github.io/lab_tutorials/4_R_Mapping.html#box-map), but it would be great to include it in classInt so that tmap could call it.

**Comment by rsbivand** [comment]
Happy to consider a PR, good idea! Because **classInt** is also used internally by **sf**, **cartography** and others, not only **tmap** could benefit.
