### ISSUE TITLE
Installing classInt on M1 Macbook

### ISSUE THREAD

**Issue by simon-tarr** [r-spatial/classInt#30]
Hello,

I'm trying to install `classInt` on an M1 Macbook. I downloaded the arm64 macOS binaries from [here](https://cran.r-project.org/web/packages/classInt/index.html) and installed with no errors with the following:
```
install.packages("~/Downloads/classInt_0.4-3.tar", repos = NULL)
```
On trying to load the library with `library(classInt)` I get the error:

```
Error: package or namespace load failed for ‘classInt’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/homebrew/lib/R/4.1/site-library/classInt/libs/classInt.so':
  dlopen(/opt/homebrew/lib/R/4.1/site-library/classInt/libs/classInt.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libgfortran.5.dylib
  Referenced from: /opt/homebrew/lib/R/4.1/site-library/classInt/libs/classInt.so
  Reason: image not found
```
Given I'm running Apple silicone, I suspected the issue was something to do with `gfortran` not being available for this architecture. After some Googling, however, I found that others had attempted this [here](https://github.com/fxcoudert/gfortran-for-macOS). I have installed this successfully, reinstalled `classInt` but still receive the error.

Could someone help me to troubleshoot, please?

**Comment by rsbivand** [comment]
Please only use `install.packages("classInt")`, and so pick up the correct binary package from CRAN. It isn't obvious where `classInt_0.4-3.tar` came from - is it an unpacked `classInt_0.4-3.tar.gz` source package, which it should not be unpacked if installing a source package. Or have you unpacked an `classInt_0.4-3.tgz`, which is already a binary package? The error message suggests the latter, but that the CRAN-built shared object does not match the expectations of your architecture or perhaps of homebrew. I do not offer advice on hombrew, by the way.
