### ISSUE TITLE
findCols()  invalid 'labels'; length 5 should be 1 or 4

### ISSUE THREAD

**Issue by JosiahParry** [r-spatial/classInt#35]
I've identified a bug with the way I've assigned factor levels that occurs when there are class intervals that contain no observations— naïveté on my part. 

Reproducible example below. 
``` r
xvar <- c(22361, 9573, 4836, 5309, 10384, 4359, 11016, 4414, 3327, 3408, 
  17816, 6909, 6936, 7990, 3758, 3569, 21965, 3605, 2181, 1892, 
  2459, 2934, 6399, 8578, 8537, 4840, 12132, 3734, 4372, 9073, 
  7508, 5203)

classInt::classify_intervals(xvar, 5, "sd", factor = FALSE)
#>  [1] 5 3 2 2 3 2 3 2 2 2 5 2 2 3 2 2 5 2 2 1 2 2 2 3 3 2 3 2 2 3 3 2
classInt::classify_intervals(xvar, 5, "sd", factor = TRUE)
#> Error in factor(cols, labels = col_vals): invalid 'labels'; length 5 should be 1 or 4
```

This is because of the way in which the factor is created where labels may be longer than unique factor levels.

https://github.com/r-spatial/classInt/blob/159a146728b32060a62d68f7332b266d5c005400/R/classInt.R#L426

Another approach could be to create a look up table, create a named vector, then cast to a factor like so: 

``` r
xvar <- c(22361, 9573, 4836, 5309, 10384, 4359, 11016, 4414, 3327, 3408, 
          17816, 6909, 6936, 7990, 3758, 3569, 21965, 3605, 2181, 1892, 
          2459, 2934, 6399, 8578, 8537, 4840, 12132, 3734, 4372, 9073, 
          7508, 5203)

clI <- classInt::classIntervals(xvar, 5, "sd")
cols <- classInt::findCols(clI)
col_vals <- names(classInt:::tableClassIntervals(cols, clI$brks))
lookup <- setNames(1:length(col_vals), col_vals)
as.factor(lookup[cols])
#>  [17640.44,22845.39]  [7230.531,12435.48)  [2025.578,7230.531) 
#>                    5                    3                    2 
#>  [2025.578,7230.531)  [7230.531,12435.48)  [2025.578,7230.531) 
#>                    2                    3                    2 
... truncated
#> Levels: 1 2 3 5
```

Additional approaches appreciated.

**Comment by rsbivand** [comment]
Used `levels=min(cols):max(cols)` to set levels explicitly.

**Comment by JosiahParry** [comment]
Just tried it out, works wonderfully. Thanks!

**Comment by rsbivand** [comment]
Is it OK to go for a CRAN submission?

**Comment by rsbivand** [comment]
Maybe we should add a `NEWS.md` file - could you suggest one by PR, perhaps?

**Comment by JosiahParry** [comment]
@rsbivand yes, I'll make a PR after work today. There's one other thing that I think is worth considering as well. The case when the minimum or maximum level have no observations. In that case I suspect that 
`factor(cols, levels = 1:length(col_vals), labels = col_vals)` may be able to handle that edge case.

**Comment by rsbivand** [comment]
Right, well caught! PR when you are ready.
