### ISSUE TITLE
How to set specific number of classes when using head/tails classification?

### ISSUE THREAD

**Issue by nikosGeography** [r-spatial/classInt#37]
Hi I want to perform `head/tails` classification to `data.frame` and I'd like to set the number of classes to 7 but I can't. The classes are set automatically to either 2 or 14. I tried different parameters like the `n = 7` and `thr = _from 0 to 1_`, without success. How can I set the number of classes to 7? Here is the code and the data.

```
library(classInt)

block.data = read.csv("path/values.csv")
vec1 <- block.data$X4

print(classIntervals(vec1, n = 7, style = "headtails", thr = 1))
```

The dataset I am sharing (20 values) is a really small subset of my original data.frame (>10K values) and it can be classified into 5 classes, while my original data.frame can be classified into 2 or 14 classes.

```
c(4.15732383728027, 4.64473390579224, 5.13697910308838, 5.62461566925049, 
6.08347082138062, 6.09681606292725, 5.98013210296631, 5.85955047607422, 
5.74385595321655, 5.69291543960571, 5.80153608322144, 5.94426155090332, 
6.10236692428589, 6.24384021759033, 4.13175535202026, 4.61712312698364, 
5.10912799835205, 5.60870552062988, 6.10747909545898)
```
Thank you.

**Comment by rsbivand** [comment]
This style does not respect or use `n=`:
https://github.com/r-spatial/classInt/blob/b829f108fbd2ae28632a838855aea50627e6a440/R/classInt.R#L308-L331
As https://r-spatial.github.io/classInt/articles/headtailsR.html shows, the `thr=` argument matters, and is upward bounded at 1 (100%), the default is 0.4 (40%).

**Comment by nikosGeography** [comment]
I know that only the `thr =` argument matters, I wanted to point out what I have tried. To be more specific, I have set values in the `thr` from 0.1 to 1 using a step of 0.05 (i.e., 0.1, 0.15, 0.2 etc) but the result is always either 2 or 14 classes. Is there any way to set the classes to 7?

**Comment by dieghernan** [comment]
Hi, 

The answer is no, there is no way to control the exact number of classes on the `headtail` method. This would depend on how the data is distributed. The `thr` may help on that but for some distributions even `thr = 1` may return only 2 classes.

 If you want a specific number maybe you can consider another classifying method.
