### ISSUE TITLE
Issues installing from source

### ISSUE THREAD

**Issue by chris-prener** [r-spatial/classInt#4]
Since the update was posted to CRAN yesterday, my Appveyor builds are failing when Appveyor tries to install `classInt` from source. An example of this can be found [here](https://ci.appveyor.com/project/chris-prener/areal/builds/21094418/job/427iyu6jbk0k02l5#L170).

The relevant section has the following:

```
There is a binary version available but the source version is later:
              binary source needs_compilation
classInt  0.2-3  0.3-1              TRUE

installing the source package 'classInt'

trying URL 'https://cran.rstudio.com/src/contrib/classInt_0.3-1.tar.gz'
Content type 'application/x-gzip' length 17320 bytes (16 KB)
==================================================
downloaded 16 KB

* installing *source* package 'classInt' ...
** package 'classInt' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gfortran      -O3  -mtune=generic -c fish1.f -o fish1.o
make: c:/Rtools/mingw_32/bin/gfortran: Command not found
make: *** [fish1.o] Error 127
ERROR: compilation failed for package 'classInt'
* removing 'c:/RLibrary/classInt'
* restoring previous 'c:/RLibrary/classInt'
Error in i.p(...) : 
 (converted from warning) installation of package 'classInt' had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
Command exited with code 1
```

This happens on all versions of [Windows](https://ci.appveyor.com/project/chris-prener/areal/builds/21094418) and also happened locally on my macOS machine when I tried to build from source. 

Thanks for checking in on this and maintaining this package - I really appreciate it!

**Comment by edzer** [comment]
Your appveyor is apparently not equipped to build from source (no gfortran available) - it should then fall back to installing the binary version on CRAN (0.2-3) or wait a few days until the binary version of the released classInt appears.

**Comment by angela-li** [comment]
I ran into a similar error when I was trying to work on `spdep` earlier - I think the problem was not having gfortran installed on my local computer. Downloading the most recent version of GNU Fortran from the [R development tools page](https://cran.r-project.org/bin/macosx/tools/) fixed my problems!

![screen shot 2018-12-18 at 12 52 10 pm](https://user-images.githubusercontent.com/15808896/50176168-4e2e1800-02c4-11e9-9071-c55bbab4087a.png)

**Comment by rsbivand** [comment]
Thanks @edzer and @angela-li for your help!

**Comment by chris-prener** [comment]
Thanks for the help @edzer and @angela-li - here is the Appveyor solution in case anyone finds their way here via Google:

```
environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true
```

Builds are working again!

**Comment by rsbivand** [comment]
@edzer : should I set up Appveyor for classInt? If so, how?

**Comment by edzer** [comment]
What for? I don't see any potential windows-specific issues in it.

**Comment by rsbivand** [comment]
OK, thanks, I'll leave it.
