### ISSUE TITLE
(converted from warning) installation of package ‘classInt’ had non-zero exit status

### ISSUE THREAD

**Issue by carlottaolivero** [r-spatial/classInt#40]
Hi, i am trying to download this package > devtools::install_github("outbreak-info/R-outbreak-info")

and I am getting the following problem:

Downloading GitHub repo outbreak-info/R-outbreak-info@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                   
 2: CRAN packages only                    
 3: None                                  
 4: Rcpp         (1.0.5  -> 1.0.9 ) [CRAN]
 5: magrittr     (1.5    -> 2.0.3 ) [CRAN]
 6: withr        (2.3.0  -> 2.5.0 ) [CRAN]
 7: utf8         (1.1.4  -> 1.2.2 ) [CRAN]
 8: fansi        (0.4.1  -> 1.0.3 ) [CRAN]
 9: tibble       (3.0.4  -> 3.1.8 ) [CRAN]
10: R6           (2.5.0  -> 2.5.1 ) [CRAN]
11: glue         (1.4.2  -> 1.6.2 ) [CRAN]
12: generics     (0.1.0  -> 0.1.3 ) [CRAN]
13: ellipsis     (0.3.1  -> 0.3.2 ) [CRAN]
14: hms          (0.5.3  -> 1.1.2 ) [CRAN]
15: crayon       (1.3.4  -> 1.5.2 ) [CRAN]
16: colorspace   (1.4-1  -> 2.0-3 ) [CRAN]
17: viridisLite  (0.3.0  -> 0.4.1 ) [CRAN]
18: RColorBrewer (1.1-2  -> 1.1-3 ) [CRAN]
19: farver       (2.0.3  -> 2.1.1 ) [CRAN]
20: DBI          (1.1.0  -> 1.1.3 ) [CRAN]
21: openssl      (1.4.3  -> 2.0.3 ) [CRAN]
22: mime         (0.9    -> 0.12  ) [CRAN]
23: jsonlite     (1.7.1  -> 1.8.2 ) [CRAN]
24: curl         (4.3    -> 4.3.3 ) [CRAN]
25: purrr        (0.3.4  -> 0.3.5 ) [CRAN]
26: stringi      (1.5.3  -> 1.7.8 ) [CRAN]
27: clipr        (0.7.1  -> 0.8.0 ) [CRAN]
28: scales       (1.1.1  -> 1.2.1 ) [CRAN]
29: isoband      (0.2.2  -> 0.2.6 ) [CRAN]
30: gtable       (0.3.0  -> 0.3.1 ) [CRAN]
31: digest       (0.6.27 -> 0.6.29) [CRAN]
32: yaml         (2.2.1  -> 2.3.5 ) [CRAN]
33: httr         (1.4.2  -> 1.4.4 ) [CRAN]
34: tidyr        (1.1.3  -> 1.2.1 ) [CRAN]
35: stringr      (1.4.0  -> 1.4.1 ) [CRAN]
36: plyr         (1.8.6  -> 1.8.7 ) [CRAN]
37: readr        (1.4.0  -> 2.1.3 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
Installing 2 packages: classInt, sf

  There are binary versions available but the source versions are later:
         binary source needs_compilation
classInt  0.4-3  0.4-8              TRUE
sf        1.0-7  1.0-8              TRUE

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) 
installing the source packages ‘classInt’, ‘sf’

trying URL 'https://cran.rstudio.com/src/contrib/classInt_0.4-8.tar.gz'
Content type 'application/x-gzip' length 438767 bytes (428 KB)
==================================================
downloaded 428 KB

trying URL 'https://cran.rstudio.com/src/contrib/sf_1.0-8.tar.gz'
Content type 'application/x-gzip' length 3472914 bytes (3.3 MB)
==================================================
downloaded 3.3 MB

* installing *source* package ‘classInt’ ...
** package ‘classInt’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c fish1.f -o fish1.o
make: gfortran: No such file or directory
make: *** [fish1.o] Error 1
ERROR: compilation failed for package ‘classInt’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/classInt’
Error: Failed to install 'outbreakinfo' from GitHub:
  **(converted from warning) installation of package ‘classInt’ had non-zero exit status**

I am using macOS Monterey 12.6
I have installed gfortran-6.1
Any help? thank you very much

**Comment by rsbivand** [comment]
Do not install source packages on macOS unless you must; always run `update.packages(type="binary", checkBuilt=TRUE)` before installing anything from github - `type="binary"` avoids source installs, and `checkBuilt=TRUE` updates stale installed packages from earlier R versions. 

Try to avoid the RStudio mirror, it seems often to be somewhat stale. 

See for example: https://cran.r-project.org/view=Spatial, section "Installing packages linking to PROJ, GDAL or GEOS" at foot. If you must install source packages, use https://mac.r-project.org/tools/ - you do not have the stipulated Fortran compiler (you say you have 6.1, for Intel 8.2, for M1 12.0.1 20220312). 

As you can see from  https://cran.r-project.org/package=classInt, both architectures are up-to-date for **classInt**, (and **sf** https://cran.r-project.org/package=sf). 

The off-CRAN and probably fragile package you are trying to install commits many sins, especially that of having many strong dependencies, you should have asked for installation help there.
